// packages/html-games-source/src/lib/canvas-in-react/Canvas.js
import React from "react"

function Canvas(props) {
  const { width = window.innerWidth, height = window.innerHeight } = props;
  return (
    <div>
      {React.Children.map(props.children, child => (
        React.cloneElement(child, {
          width: width,
          height: height,
        })
      ))}
    </div>
  )
}

export default Canvas;

// packages/solid-canvas/lib/canvas/index.tsx
import { Component, createEffect } from "solid-js";
import { size, setSize } from "../common/size";

const Canvas: Component = (props) => {
  createEffect(() => {
    setSize({
      width: window.innerWidth,
      height: window.innerHeight,
    });
  }, []);
  return (
    <div style={{ width: size().width, height: size().height }}>
      {props.children}
    </div>
  );
};

export default Canvas;
